name = "CharacteristicSet"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CharacteristicSet", "CharSetTac", "WuGeometry", "WuDifferential"]
[[lean_lib]]
name = "CharacteristicSet"

[[lean_lib]]
name = "CharSetTac"

[[lean_lib]]
name = "WuGeometry"

[[lean_lib]]
name = "WuDifferential"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
# `show` may only restate a goal; if it *changes* the goal, `change` is required.
weak.linter.style.show = true
maxSynthPendingDepth = 3


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.33.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"
