/-
Copyright (c) 2026 Wu tactic contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import CharSetTac.Differential
import Mathlib.RingTheory.Ideal.Operations

/-!
# Differential ideals, saturation, and certified ideal equality

The pieces needed to justify a computed chain *per instance*, without Rosenfeld's lemma.

## The idea

Wu's method computes a chain `C` from inputs `A`. The claim one wants is

```
[A] : H^∞  =  [C] : H^∞
```

Both inclusions are **positive membership statements**, and positive statements are exactly
what certificates prove:

* `[C] ⊆ [A] : H^∞` — every `Cᵢ` is produced from the `Aⱼ` by prolongation and
  pseudo-division, and cofactor tracking hands us `Hᵢ·Cᵢ = ∑ c·δᵏ(Aⱼ)` directly.
* `[A] ⊆ [C] : H^∞` — this is the algorithm's *termination condition*: it stops precisely
  when every `Aⱼ` reduces to zero modulo `C`, and that reduction is a certificate
  `H'ⱼ·Aⱼ = ∑ d·δᵏ(Cᵢ)`.

So the equality is certifiable with machinery that already exists. What Rosenfeld's lemma
uniquely buys is the *negative* direction — concluding `p ∉ [C] : H^∞` from a nonzero
remainder — which no certificate can deliver.

## The one lemma that needs proving

That `I : h^∞` is a differential ideal when `I` is. It follows from Leibniz:

`H^{n+1}·δp = H·δ(H^n p) − n·(δH)·(H^n p)`

and both terms lie in `I` when `H^n p` does. Everything else here is bookkeeping.
-/

open scoped Differential

namespace Wu

variable {R : Type*} [CommRing R] [Differential R]

/-- The `n`-th derivative. -/
def dnth (n : ℕ) (x : R) : R := (fun y : R => y′)^[n] x

@[simp] theorem dnth_zero (x : R) : dnth 0 x = x := rfl

theorem dnth_succ (n : ℕ) (x : R) : dnth (n + 1) x = (dnth n x)′ := by
  simp [dnth, Function.iterate_succ_apply']

/-- All iterated derivatives of elements of `S`. -/
def prolongations (S : Set R) : Set R := {x | ∃ s ∈ S, ∃ n : ℕ, x = dnth n s}

theorem mem_prolongations (S : Set R) {s : R} (hs : s ∈ S) (n : ℕ) :
    dnth n s ∈ prolongations S := ⟨s, hs, n, rfl⟩

/-- Prolongations are closed under differentiation. -/
theorem prolongations_deriv {S : Set R} {x : R} (hx : x ∈ prolongations S) :
    x′ ∈ prolongations S := by
  obtain ⟨s, hs, n, rfl⟩ := hx
  exact ⟨s, hs, n + 1, (dnth_succ n s).symm⟩

/-- The **differential ideal** generated by `S`: the ideal generated by all iterated
derivatives of its elements. -/
def diffIdeal (S : Set R) : Ideal R := Ideal.span (prolongations S)

theorem dnth_mem_diffIdeal (S : Set R) {s : R} (hs : s ∈ S) (n : ℕ) :
    dnth n s ∈ diffIdeal S :=
  Ideal.subset_span (mem_prolongations S hs n)

theorem self_mem_diffIdeal (S : Set R) {s : R} (hs : s ∈ S) : s ∈ diffIdeal S :=
  dnth_mem_diffIdeal S hs 0

/-- A differential ideal really is closed under the derivation.

The generators are closed under `δ` by `prolongations_deriv`; Leibniz carries that through
products, and additivity through sums. -/
theorem diffIdeal_deriv_mem {S : Set R} {x : R} (hx : x ∈ diffIdeal S) :
    x′ ∈ diffIdeal S := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hx
  · intro y hy
    exact Ideal.subset_span (prolongations_deriv hy)
  · rw [map_zero]; exact (diffIdeal S).zero_mem
  · intro a b _ _ ha hb
    rw [map_add]
    exact (diffIdeal S).add_mem ha hb
  · intro c a hamem ha
    -- `δ(c * a) = c * δa + a * δc`: the first factor uses the induction hypothesis,
    -- the second uses that `a` itself is in the ideal.
    rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    exact (diffIdeal S).add_mem (Ideal.mul_mem_left _ c ha) (Ideal.mul_mem_right _ _ hamem)

/-! ### Saturation -/

/-- The saturation `I : h^∞ = {x | ∃ n, hⁿ · x ∈ I}`.

This is where the initials and separants go: a Wu certificate proves `H · g ∈ I`, i.e.
`g` is in the saturation, not in `I` itself. -/
def sat (I : Ideal R) (h : R) : Ideal R where
  carrier := {x | ∃ n : ℕ, h ^ n * x ∈ I}
  zero_mem' := ⟨0, by simpa using I.zero_mem⟩
  add_mem' := by
    rintro a b ⟨m, hm⟩ ⟨n, hn⟩
    refine ⟨m + n, ?_⟩
    have : h ^ (m + n) * (a + b) = h ^ n * (h ^ m * a) + h ^ m * (h ^ n * b) := by ring
    rw [this]
    exact I.add_mem (Ideal.mul_mem_left _ _ hm) (Ideal.mul_mem_left _ _ hn)
  smul_mem' := by
    rintro c a ⟨n, hn⟩
    refine ⟨n, ?_⟩
    have : h ^ n * (c • a) = c * (h ^ n * a) := by rw [smul_eq_mul]; ring
    rw [this]
    exact Ideal.mul_mem_left _ _ hn

theorem mem_sat {I : Ideal R} {h x : R} : x ∈ sat I h ↔ ∃ n : ℕ, h ^ n * x ∈ I := Iff.rfl

theorem le_sat (I : Ideal R) (h : R) : I ≤ sat I h := fun x hx => ⟨0, by simpa using hx⟩

/-- **The saturation of a differential ideal is a differential ideal.**

This is the one lemma the per-instance certification needs. Multiplying through by `hⁿ`
rather than `h` avoids any case split on `n`:

`h^{2n} · x′ = hⁿ · (hⁿx)′ − (hⁿ)′ · (hⁿx)`

and both terms are in `I` when `hⁿx` is — the first because `I` is closed under `δ`, the
second because it is a multiple of `hⁿx`. -/
theorem sat_diffIdeal_deriv_mem {S : Set R} {h x : R}
    (hx : x ∈ sat (diffIdeal S) h) : x′ ∈ sat (diffIdeal S) h := by
  obtain ⟨n, hn⟩ := hx
  refine ⟨2 * n, ?_⟩
  have hd : (h ^ n * x)′ ∈ diffIdeal S := diffIdeal_deriv_mem hn
  have key : h ^ (2 * n) * x′ = h ^ n * (h ^ n * x)′ - (h ^ n)′ * (h ^ n * x) := by
    rw [Derivation.leibniz]
    simp only [smul_eq_mul, two_mul, pow_add]
    ring
  rw [key]
  exact (diffIdeal S).sub_mem (Ideal.mul_mem_left _ _ hd) (Ideal.mul_mem_left _ _ hn)

/-! ### Certified membership and ideal equality -/

/-- A differential ideal is the *smallest* δ-closed ideal containing its generators. -/
theorem diffIdeal_le {A : Set R} {J : Ideal R}
    (hδ : ∀ x ∈ J, x′ ∈ J) (hA : A ⊆ J) : diffIdeal A ≤ J := by
  refine Ideal.span_le.mpr ?_
  rintro y ⟨t, ht, n, rfl⟩
  induction n with
  | zero => simpa using hA ht
  | succ m ih => rw [dnth_succ]; exact hδ _ ih

/-- **A Wu certificate witnesses membership in the saturated differential ideal.**

This is the bridge. `H * g = ∑ᵢ cᵢ · δ^{kᵢ}(aᵢ)` with each `aᵢ` an input gives
`g ∈ [A] : H^∞` — no Rosenfeld, no coherence, no completeness claim. Each `δ^{kᵢ}(aᵢ)` is a
generator of the differential ideal, and the rest is `Ideal.sum_mem`. -/
theorem mem_sat_of_certificate {A : Set R} {g H : R} {ι : Type*} (s : Finset ι)
    (c a : ι → R) (k : ι → ℕ) (ha : ∀ i ∈ s, a i ∈ A)
    (hcert : H * g = ∑ i ∈ s, c i * dnth (k i) (a i)) :
    g ∈ sat (diffIdeal A) H := by
  refine ⟨1, ?_⟩
  rw [pow_one, hcert]
  exact Submodule.sum_mem _ fun i hi =>
    Ideal.mul_mem_left _ _ (dnth_mem_diffIdeal A (ha i hi) (k i))

/-- **Per-instance certification of the computed chain.**

If every input lies in the chain's saturation and every chain element lies in the inputs'
saturation — both of which the algorithm's own certificates give — then the two saturated
differential ideals coincide.

This is the structure theorem Rosenfeld's lemma would hand over for free, obtained instead
one instance at a time. What is *not* obtained is non-membership: this says the two ideals
agree, not that anything is outside them. -/
theorem sat_diffIdeal_eq_of_mem {A C : Set R} {H : R}
    (hAC : ∀ x ∈ A, x ∈ sat (diffIdeal C) H)
    (hCA : ∀ x ∈ C, x ∈ sat (diffIdeal A) H) :
    sat (diffIdeal A) H = sat (diffIdeal C) H := by
  have step : ∀ {X Y : Set R}, (∀ x ∈ X, x ∈ sat (diffIdeal Y) H) →
      sat (diffIdeal X) H ≤ sat (diffIdeal Y) H := by
    intro X Y hXY x hx
    obtain ⟨n, hn⟩ := hx
    have hle : diffIdeal X ≤ sat (diffIdeal Y) H :=
      diffIdeal_le (fun _ h => sat_diffIdeal_deriv_mem h) hXY
    obtain ⟨m, hm⟩ := hle hn
    exact ⟨m + n, by rw [pow_add, mul_assoc]; exact hm⟩
  exact le_antisymm (step hAC) (step hCA)

end Wu
