/-
Copyright (c) 2026 Wu tactic contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import CharSetTac.StructureSheafDeriv
import Mathlib.Algebra.MvPolynomial.PDeriv

/-!
# Differential ideals and the differential spectrum

Item B step 2, and the last piece of Item B. `CharSetTac/DiffIdeal.lean` has the *ideal
generated by* prolongations; what was missing is the **predicate** — an ideal closed under
the derivation — and everything that follows from it.

Stated for a general `Derivation R A A` rather than Mathlib's `Differential` class, matching
`StructureSheafDeriv.lean` and for the same reason: `Differential` fixes the base to `ℤ` and
puts its `Module ℤ` on the wrong side of the `Algebra`/`AddCommGroup` diamond.

## What this is for

`Spec^Δ(A)` is the subspace of `Spec A` on the primes that are differential ideals. The
structure presheaf of `StructureSheafDeriv.lean` lives on all of `Spec A`; the differential
spectrum is where the *geometry* is, because a point of `Spec^Δ` is a differential
specialisation — a prime that the flow of `d` preserves.

The concrete payoff here is `isDiffIdeal_map_of_diffPrime`: localizing at a
differential prime gives a local ring whose maximal ideal is again differential. That is
what makes a differential-scheme stalk a *differential local ring* rather than merely a
local ring that happens to carry a derivation.
-/

open AlgebraicGeometry StructureSheaf TopologicalSpace

namespace Wu

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-! ### Differential ideals -/

/-- An ideal closed under the derivation. -/
def IsDiffIdeal (d : Derivation R A A) (I : Ideal A) : Prop := ∀ x ∈ I, d x ∈ I

namespace IsDiffIdeal

variable {d : Derivation R A A} {I J : Ideal A}

theorem bot : IsDiffIdeal d ⊥ := fun x hx => by
  rw [Ideal.mem_bot] at hx ⊢; simp [hx]

theorem top : IsDiffIdeal d ⊤ := fun _ _ => Submodule.mem_top

theorem inf (hI : IsDiffIdeal d I) (hJ : IsDiffIdeal d J) : IsDiffIdeal d (I ⊓ J) :=
  fun _ hx => ⟨hI _ hx.1, hJ _ hx.2⟩

theorem iInf {ι : Type*} {f : ι → Ideal A} (h : ∀ i, IsDiffIdeal d (f i)) :
    IsDiffIdeal d (⨅ i, f i) := fun x hx => by
  rw [Submodule.mem_iInf] at hx ⊢
  exact fun i => h i x (hx i)

/-- **An ideal is differential as soon as its generators are.** The Leibniz rule does the
rest: `d (c * x) = c · d x + x · d c`, and both summands are in the ideal once `x` is. -/
theorem of_span {S : Set A} (h : ∀ x ∈ S, d x ∈ Ideal.span S) :
    IsDiffIdeal d (Ideal.span S) := by
  intro x hx
  induction hx using Submodule.span_induction with
  | mem y hy => exact h y hy
  | zero => simp
  | add y z _ _ hy hz => rw [map_add]; exact Submodule.add_mem _ hy hz
  | smul c y hy hcy =>
      rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      exact Submodule.add_mem _ (Ideal.mul_mem_left _ _ hcy)
        (Ideal.mul_mem_right _ _ hy)

end IsDiffIdeal

/-! ### The differential spectrum -/

/-- **The differential spectrum**: primes closed under the derivation, as a subspace of
`Spec A`.

A subtype rather than a fresh structure, so that the topology, the specialisation order and
everything else about `PrimeSpectrum` come along for free. -/
def DiffPrimeSpectrum (d : Derivation R A A) : Type _ :=
  {P : PrimeSpectrum A // IsDiffIdeal d P.asIdeal}

namespace DiffPrimeSpectrum

variable {d : Derivation R A A}

instance : TopologicalSpace (DiffPrimeSpectrum d) :=
  inferInstanceAs (TopologicalSpace {P : PrimeSpectrum A // _})

/-- The inclusion into the full spectrum. -/
def toPrimeSpectrum (P : DiffPrimeSpectrum d) : PrimeSpectrum A := P.1

theorem toPrimeSpectrum_injective : Function.Injective (toPrimeSpectrum (d := d)) :=
  fun _ _ h => Subtype.ext h

/-- The inclusion is a topological embedding: the differential spectrum carries the
subspace topology, by construction. -/
theorem isEmbedding_toPrimeSpectrum :
    Topology.IsEmbedding (toPrimeSpectrum (d := d)) :=
  Topology.IsEmbedding.subtypeVal

end DiffPrimeSpectrum

/-! ### Localizing at a differential prime -/

/-- **The maximal ideal of a stalk at a differential prime is again differential.**

This is what makes the stalk a *differential* local ring. The computation is the quotient
rule: `d(p/s) = (s·dp - p·ds)/s²`, and both `dp` and `p` lie in `P`, so the numerator does
too.

Note where the hypothesis is used — `dp ∈ P` is exactly `IsDiffIdeal`, and without it the
first summand escapes. -/
theorem isDiffIdeal_map_of_diffPrime (d : Derivation R A A) (P : PrimeSpectrum A)
    (hP : IsDiffIdeal d P.asIdeal) :
    IsDiffIdeal (stalkDeriv d P)
      (P.asIdeal.map (algebraMap A (Localizations A P))) := by
  rw [Ideal.map]
  apply IsDiffIdeal.of_span
  rintro _ ⟨p, hp, rfl⟩
  rw [stalkDeriv, Derivation.localization_algebraMap]
  exact Submodule.subset_span ⟨d p, hP p hp, rfl⟩

/-! ### A differential prime, and a prime that is not

Differential primes are genuinely special, and the smallest examples show why. -/

/-- In a domain the zero ideal is a differential prime: closed under `d` because `d 0 = 0`,
and prime because there are no zero divisors. -/
theorem isDiffIdeal_bot_of_isDomain [IsDomain A] (d : Derivation R A A) :
    IsDiffIdeal d (⊥ : Ideal A) ∧ (⊥ : Ideal A).IsPrime :=
  ⟨IsDiffIdeal.bot, Ideal.isPrime_bot⟩

/-- **`(X)` is prime but not differential** for `∂/∂X` on a polynomial ring: `d X = 1`, which
is not in `(X)`.

Worth recording as the counterexample that makes `DiffPrimeSpectrum` a proper subspace
rather than all of `Spec`. A differential ideal must be closed under `d`, and the ideal of
functions vanishing at a point is generally not — the flow moves the point. -/
theorem not_isDiffIdeal_span_X (σ : Type*) (i : σ) :
    ¬ IsDiffIdeal (MvPolynomial.pderiv i)
        (Ideal.span {MvPolynomial.X i} : Ideal (MvPolynomial σ ℚ)) := by
  intro h
  have h1 : (1 : MvPolynomial σ ℚ) ∈ Ideal.span {MvPolynomial.X i} := by
    have := h _ (Submodule.subset_span rfl)
    simpa using this
  rw [Ideal.mem_span_singleton] at h1
  -- `1 = X i * p` cannot hold: evaluate at the origin
  obtain ⟨p, hp⟩ := h1
  have := congrArg (MvPolynomial.eval (fun _ => (0 : ℚ))) hp
  simp at this

end Wu
