/-
Copyright (c) 2026 Wu tactic contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import CharSetTac.DiffPolynomial
import CharSetTac.DiffSpec

/-!
# `R{y}` in use

`CharSetTac/DiffPolynomial.lean` builds the differential polynomial ring and proves it is the
free differential algebra. This file is the demonstration: what the object is for, and what
the universal property actually buys.

Everything is over `ℚ` in one unknown, so `y[k]` is `y^(k)`. Nothing here is `sorry`, and
nothing is `native_decide` — these are ordinary proofs.

## What the four sections show

1. **The derivation computes.** Leibniz on a product of derivatives, which is the calculation
   the tactic's prolongation step performs on every hypothesis.
2. **The differential ideal of an ODE.** The ideal generated by `y' - y` and all its
   prolongations is closed under `d`. This is the setting of Ritt–Raudenbush, and it is the
   first place `DiffPolynomial` and `IsDiffIdeal` meet.
3. **Evaluation at a solution.** A differential polynomial is a *function of a solution* once
   you say where `y` goes; `evalDiff` is that substitution, and it is forced.
4. **Solutions stay solutions.** `evalDiff_deriv` is not decoration: it means a specialisation
   that kills an equation automatically kills every prolongation of it. That is the entire
   reason the universal property is worth proving.
-/

open MvPolynomial

namespace Wu.DiffPolynomialExamples

/-- `y[k]` is `y^(k)`, the `k`-th derivative of the single unknown. -/
local notation "y[" k "]" => Wu.DiffPolynomial.Y (() : Unit) k

/-- `d` is the derivation of `ℚ{y}`. Written out rather than `open`ed, because
`Wu.DiffPolynomial.deriv` would otherwise clash with Mathlib's analytic `deriv`. -/
local notation "d" => Wu.DiffPolynomial.deriv ℚ Unit

/-! ### 1. The derivation computes

`d` is determined by `y^(k) ↦ y^(k+1)` and the Leibniz rule, and that is enough to
differentiate anything. -/

/-- `(y·y')' = y·y'' + (y')²`. -/
example : d (y[0] * y[1]) = y[0] * y[2] + y[1] * y[1] := by
  rw [Derivation.leibniz]
  simp [smul_eq_mul]

/-- `(y²)' = 2·y·y'`. -/
example : d (y[0] ^ 2) = 2 * (y[0] * y[1]) := by
  rw [Derivation.leibniz_pow]
  simp [smul_eq_mul]

/-- **Prolongation.** Differentiating the ODE `y' - y = 0` gives `y'' - y' = 0`. This single
step is what `wu_pde` does to every hypothesis, here performed inside the free object where
it is definitionally the shift `k ↦ k+1`. -/
example : d (y[1] - y[0]) = y[2] - y[1] := by simp

/-! ### 2. The differential ideal of an ODE

The equations that follow from `y' = y` by differentiation and ring operations form an ideal
closed under `d`. Generating it needs *all* the prolongations — the ideal generated by
`y' - y` alone is not differential, since `d(y' - y) = y'' - y'` is not a multiple of it. -/

/-- The ODE `y' = y` together with all of its prolongations: `y^(k+1) - y^(k)` for every `k`. -/
def expOde : Set (Wu.DiffPolynomial ℚ Unit) :=
  Set.range fun k : ℕ => y[k + 1] - y[k]

/-- **The prolongation-closed ideal of `y' = y` is a differential ideal.**

`IsDiffIdeal.of_span` reduces this to checking the generators, and differentiating the `k`-th
generator lands exactly on the `(k+1)`-st — which is why the generating set had to include
every prolongation. -/
theorem isDiffIdeal_expOde :
    IsDiffIdeal (Wu.DiffPolynomial.deriv ℚ Unit) (Ideal.span expOde) := by
  apply IsDiffIdeal.of_span
  rintro _ ⟨k, rfl⟩
  exact Submodule.subset_span ⟨k + 1, by simp⟩

/-! ### 3. Evaluation at a solution

To give a differential algebra map out of `ℚ{y}` is to say where `y` goes — that is the
universal property. Sending `y ↦ t` in `ℚ[t]` with `d/dt` forces `y' ↦ 1` and `y^(k) ↦ 0`
for `k ≥ 2`, with no further choice available. -/

/-- Substituting `y := t`, into `ℚ[t]` with `∂/∂t`. -/
noncomputable def atT : Wu.DiffPolynomial ℚ Unit →ₐ[ℚ] MvPolynomial Unit ℚ :=
  Wu.DiffPolynomial.evalDiff (pderiv ()) fun _ => X ()

example : atT y[0] = X () := by simp [atT]

example : atT y[1] = 1 := by simp [atT]

example : atT y[2] = 0 := by simp [atT]

/-- A whole differential polynomial evaluated at `y := t`: `y·y'' - (y')²` becomes
`t·0 - 1² = -1`. -/
example : atT (y[0] * y[2] - y[1] ^ 2) = -1 := by
  simp [atT]

/-- **`t` is a solution of `y'' = 0`** — which is what it means for the substitution to kill
the differential polynomial `y''`. -/
theorem atT_second_deriv : atT y[2] = 0 := by simp [atT]

/-! ### 4. Solutions stay solutions

Here is the payoff. `evalDiff_deriv` says the substitution intertwines the two derivations, so
a specialisation that kills an equation kills every prolongation of it *for free* — no
recomputation, no induction at the call site. -/

/-- `t` solves `y'' = 0`, hence it solves `y''' = 0` — obtained by pushing the derivation
across the substitution rather than by evaluating anything. -/
example : atT (d y[2]) = 0 := by
  rw [atT, Wu.DiffPolynomial.evalDiff_deriv, ← atT, atT_second_deriv, map_zero]

/-- **Uniqueness.** Any `ℚ`-algebra map that commutes with the derivations and sends `y` to
`t` *is* `atT`. This is what makes "substituting a solution" a well-defined notion rather
than a construction that happened to work. -/
example (g : Wu.DiffPolynomial ℚ Unit →ₐ[ℚ] MvPolynomial Unit ℚ)
    (hcomm : ∀ p, g (d p) = pderiv () (g p)) (hy : g y[0] = X ()) :
    g = atT :=
  Wu.DiffPolynomial.evalDiff_unique _ _ g hcomm fun _ => hy

end Wu.DiffPolynomialExamples
