/-
Copyright (c) 2026 Wu tactic contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import WuDifferential.Basic

/-!
# Differential consequences proved by `wu`

The differential counterpart of `WuGeometry/Theorems.lean`. Each theorem states that a
relation follows from a system of ODEs, and is proved by prolonging the hypotheses (the
only differential step) and then running the algebraic engine with derivatives as atoms.

## What is and is not in scope

Everything here is a **single derivation** — ordinary differential equations. That is not
an accident of convenience: with one derivation a pairwise partially reduced triangular
set has no critical pairs, so coherence holds vacuously and none of the Rosenfeld
machinery is needed.

**Gauss–Codazzi is therefore out of scope**, and it is worth being precise about why. The
Gauss and Codazzi–Mainardi equations are PDEs in the two surface parameters `(u, v)`, i.e.
*two* derivations. That is exactly the "partial case" in which two chain elements can have
leading derivatives of a common indeterminate, critical pairs appear, and coherence stops
being automatic. Reaching it needs a multi-index `DiffAtom` and Δ-polynomials, not just
more examples.

The genuine differential geometry that *is* single-derivation appears below: the
Frenet–Serret relations for curves, and the unit-speed profile identity which is the
surface-of-revolution reduction of the Gauss equation.

## Why the prolongations are explicit

Each proof names the derivative of a hypothesis with a `have`. That step is mechanical and
is what `wu_diff` will automate; until then it is written out, which has the advantage of
making visible exactly which prolongation each theorem needs.
-/

open scoped Differential

namespace WuDiff

-- `CharZero` is needed, not cosmetic: differentiating a square produces a factor `2`,
-- and in characteristic 2 that factor genuinely vanishes.
variable {R : Type*} [CommRing R] [IsDomain R] [CharZero R] [Differential R]

/-! ### Elementary ODE consequences -/

/-- `y′ = y` implies `y″ = y`. -/
theorem exp_second (y : R) (h : y′ = y) : (y′)′ = y := by
  have h' : (y′)′ = y′ := Wu.deriv_congr h
  wu

/-- `y′ = y²` implies `y″ = 2y³`: the prolongation genuinely uses Leibniz. -/
theorem sq_second (y : R) (h : y′ = y ^ 2) : (y′)′ = 2 * y ^ 3 := by
  have h' : (y′)′ = 2 * y * y′ := by
    rw [Wu.deriv_congr h, pow_two, deriv_mul]; ring
  wu

/-- The logistic equation `y′ = y(1 - y)` implies `y″ = y(1-y)(1-2y)`. -/
theorem logistic_second (y : R) (h : y′ = y * (1 - y)) :
    (y′)′ = y * (1 - y) * (1 - 2 * y) := by
  have h' : (y′)′ = y′ - 2 * y * y′ := by
    rw [Wu.deriv_congr h]
    simp only [mul_sub, mul_one, map_sub, deriv_mul]
    ring
  wu

/-! ### Conserved quantities -/

/-- The harmonic oscillator conserves `u² + v²`. -/
theorem harmonic_energy (u v : R) (h₁ : u′ = v) (h₂ : v′ = -u) :
    (u * u + v * v)′ = 0 := by
  have hL : (u * u + v * v)′ = 2 * u * u′ + 2 * v * v′ := by
    rw [map_add, deriv_sq, deriv_sq]
  wu

/-- The SIR epidemic model conserves total population.

`S′ = -βSI`, `I′ = βSI - γI`, `R′ = γI`, so `(S + I + R)′ = 0`. -/
theorem sir_population (S I Rc β γ : R) (hβ : β′ = 0) (hγ : γ′ = 0)
    (hS : S′ = -(β * S * I)) (hI : I′ = β * S * I - γ * I) (hR : Rc′ = γ * I) :
    (S + I + Rc)′ = 0 := by
  have hL : (S + I + Rc)′ = S′ + I′ + Rc′ := by rw [map_add, map_add]
  wu (vars := [β, γ, S, I, Rc, S′, I′, Rc′, (S + I + Rc)′])

/-! ### Differential geometry: curves -/

/-- Frenet–Serret in the plane: the unit tangent stays a unit vector.

With `T = (T₁, T₂)` and normal `N = (-T₂, T₁)`, the Frenet equation `T′ = κN` reads
`T₁′ = -κT₂`, `T₂′ = κT₁`. Then `|T|²` is constant. -/
theorem frenet_plane_unit (T₁ T₂ κ : R) (hκ : κ′ = 0)
    (h₁ : T₁′ = -(κ * T₂)) (h₂ : T₂′ = κ * T₁) :
    (T₁ * T₁ + T₂ * T₂)′ = 0 := by
  have hL : (T₁ * T₁ + T₂ * T₂)′ = 2 * T₁ * T₁′ + 2 * T₂ * T₂′ := by
    rw [map_add, deriv_sq, deriv_sq]
  wu (vars := [κ, T₁, T₂, T₁′, T₂′, (T₁ * T₁ + T₂ * T₂)′])

/-- Frenet–Serret in space: the tangent and normal stay orthogonal.

Working with the scalar products `a = T·T`, `b = N·N`, `d = T·N`, `e = T·B`, the Frenet
equations `T′ = κN`, `N′ = -κT + τB` give `d′ = κb - κa + τe`. On a unit-speed curve with
an orthonormal frame (`a = b = 1`, `e = 0`) this vanishes. -/
theorem frenet_space_orthogonal (a b d e κ τ : R)
    (ha : a = 1) (hb : b = 1) (he : e = 0)
    (hd : d′ = κ * b - κ * a + τ * e) :
    d′ = 0 := by wu

/-- Unit-speed profile curve: `f′² + g′² = 1` implies `f′f″ + g′g″ = 0`.

This is the surface-of-revolution reduction of the Gauss equation: for a surface of
revolution generated by `(f(s), g(s))`, the profile being unit speed is exactly this
constraint, and the identity below is what makes the Gaussian curvature `-f″/f` well
behaved. It is the one derivation shadow of Gauss–Codazzi.

`g′ ≠ 0` is required by the *method*, not by the mathematics: the identity holds outright,
but the goal `f′f″ + g′g″` has initial `f′` or `g′` in whichever second derivative is
eliminated, so pseudo-division must divide by one of them. Geometrically it says the
profile is not instantaneously horizontal. -/
theorem unit_speed_profile (f g : R) (hg : g′ ≠ 0) (h : f′ * f′ + g′ * g′ = 1) :
    f′ * (f′)′ + g′ * (g′)′ = 0 := by
  have hL : (f′ * f′ + g′ * g′)′ = 2 * f′ * (f′)′ + 2 * g′ * (g′)′ := by
    rw [map_add, deriv_sq, deriv_sq]
  have h0 : (f′ * f′ + g′ * g′)′ = 0 := by rw [h]; simp
  wu (vars := [f, g, f′, g′, (f′)′, (g′)′, (f′ * f′ + g′ * g′)′])

/-! ### Elimination: the identifiability shape -/

/-- Lotka–Volterra input–output relation.

Observing only the prey `x`, eliminate the predator `y` from
`x′ = x(α - βy)`, `y′ = y(δx - γ)` to obtain a relation in `x, x′, x″` alone:

`x·x″ - x′² + x(αx - x′)(δx - γ) = 0`.

This is the shape structural identifiability analysis needs — the input–output relation
whose coefficients determine which parameter combinations are recoverable from data. It is
a *positive* claim (this relation holds), which is exactly what a certificate proves;
claiming it is the *complete* set of relations would need Rosenfeld's lemma. -/
theorem lotka_volterra_io (x y α β γ δ : R)
    (hx0 : x ≠ 0) (hβ0 : β ≠ 0) (hy0 : x * α - x′ ≠ 0)
    (hα : α′ = 0) (hβ : β′ = 0) (hγ : γ′ = 0) (hδ : δ′ = 0)
    (hx : x′ = x * (α - β * y)) (hy : y′ = y * (δ * x - γ)) :
    x * (x′)′ - x′ * x′ + x * (α * x - x′) * (δ * x - γ) = 0 := by
  have hx' : (x′)′ = x′ * (α - β * y) - x * (β * y′) := by
    rw [Wu.deriv_congr hx, deriv_mul, map_sub, deriv_mul, hα, hβ]
    ring
  wu

end WuDiff
