/-
Copyright (c) 2026 Wu tactic contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import CharSetTac.DiffFrontend
import WuDifferential.Basic
import WuDifferential.Variational

/-!
# Where `wu_diff` helps in the variational bicomplex — and where it does not

## The honest answer first

**For the structural theorems of the bicomplex, `wu_diff` is no help at all.** `E ∘ D = 0`,
`d = d_H + d_V`, `d_V y^(k) = θ_k`, `prolong_deriv` — every one is proved by
`MvPolynomial.derivation_ext`: both sides are derivations, so they agree as soon as they
agree on generators. That is a structural argument about maps, not an ideal membership, and
there is nothing for a characteristic-set engine to do.

**It earns its keep one layer down: statements that hold _on solutions_.** "On solutions of
`E(L) = 0`" means "modulo the differential ideal generated by `E(L)` and its prolongations",
and deciding *that* is exactly what `wu_diff` computes. Noether's theorem, first integrals
and every classical conservation law live there.

| Layer | Statement | Tool |
|---|---|---|
| Bicomplex structure | `E ∘ D = 0`, `d = d_H + d_V` | `derivation_ext` |
| Computing `E(L)` for a given `L` | `euler 5 L = …` | `simp` + `ring` in `ℚ{y}` |
| **Consequences on solutions** | **`D H = 0` given `E(L) = 0`** | **`wu_diff`** |

## The example

A second-order nonlinear Lagrangian — the stabilised-elastica / Swift–Hohenberg family:

```
  L = (y'')² − (y')² + y⁴
```

Its Euler–Lagrange expression, computed below in `ℚ{y}` rather than asserted, is **fourth
order**: `E(L) = 4y³ + 2y'' + 2y⁗`. Since `L` carries no explicit `x`, the higher-order
Beltrami identity applies and the energy

```
  H = y⁴ + (y')² + 2y'y''' − (y'')²
```

satisfies `D H = 2y'·E(L)`, so it is constant on solutions. That is Noether's theorem for
translation in the independent variable, at second order.

## Writing this example changed the tactic

`wu_diff` could not do any of it. It prolonged the *hypotheses* and never touched the
*conclusion*, so a goal of the shape `δ(H) = 0` reflected `δ(H)` as one opaque atom and the
engine reported that the goal did not follow — on the harmonic oscillator, not just here.
Since every conservation law has that shape, the frontend was missing the half that matters.
`Wu.expandGoal` in `CharSetTac/DiffFrontend.lean` is the fix.

## What `wu_diff` actually does, in three jobs

1. **Prolongation** — differentiating hypotheses, so a fourth-order hypothesis can meet a
   sixth-order goal.
2. **Leibniz expansion** — of hypotheses *and* now the goal.
3. **Finding the cofactors** — the multipliers `d_j` with `I·(lhs − rhs) = Σ d_j h_j`.

The hand proofs below do 1 and 2 explicitly and are *told* the answer to 3. Job 3 is Wu's
method proper and the one that stops being guessable first.
-/

open scoped Differential

namespace WuDifferential.VariationalWu

/-! ### 1. Computing the Euler–Lagrange expression, in `ℚ{y}`

The bicomplex layer: no hypotheses, no tactic cleverness. `euler` is a finite alternating
sum, so this is `simp`. -/

section Symbolic

open Wu.Variational

local notation "y[" k "]" => Wu.DiffPolynomial.Y (() : Unit) k

/-- **`E(L)` for `L = (y'')² − (y')² + y⁴`.** Fourth order, because `∂L/∂y''` is
differentiated twice. -/
example :
    euler 5 (y[2] ^ 2 - y[1] ^ 2 + y[0] ^ 4)
      = 4 * y[0] ^ 3 + 2 * y[2] + 2 * y[4] := by
  simp [euler, Finset.sum_range_succ, Derivation.leibniz_pow]

end Symbolic

/-! ### 2. Consequences on solutions, in a differential ring

Now `E(L) = 0` is a *hypothesis*. `CharZero` is load-bearing: differentiating a square
produces a factor `2`. -/

variable {R : Type*} [CommRing R] [IsDomain R] [CharZero R] [Differential R]

/-! #### The Beltrami identity -/

/-- **`H` is a first integral — by hand.**

No prolongation is needed (hypothesis and goal are both fourth order), but the Leibniz
expansion is, and the cofactor `2y'` has to be supplied. -/
theorem beltrami_by_hand (y : R)
    (h : y′′′′ + y′′ + 2 * y ^ 3 = 0) :
    (y ^ 4 + (y′) ^ 2 + 2 * (y′ * y′′′) - (y′′) ^ 2)′ = 0 := by
  simp only [map_add, map_sub, Derivation.leibniz, Derivation.leibniz_pow,
    smul_eq_mul, nsmul_eq_mul, Nat.cast_ofNat, Derivation.map_ofNat, mul_zero, add_zero,
    Nat.add_one_sub_one, pow_one]
  linear_combination (2 * y′) * h

/-- **The same, by `wu_diff`.** Expansion and cofactor both found.

The variable order is given explicitly, and it matters — see the note below. -/
theorem beltrami_by_wu (y : R)
    (h : y′′′′ + y′′ + 2 * y ^ 3 = 0) :
    (y ^ 4 + (y′) ^ 2 + 2 * (y′ * y′′′) - (y′′) ^ 2)′ = 0 := by
  wu_diff (vars := [y, y′, y′′, y′′′, y′′′′, y′′′′′])

/-! **Why the `vars` clause is there, and what happens without it.**

Bare `wu_diff` also finds a certificate, but a worse one: it picks up a multiplier `6y²` and
leaves the nondegeneracy side goal `¬ y = 0`. The identity is unconditional, so that
condition is spurious — an artefact of the default variable order, which is first-appearance
across the hypotheses.

This is not a defect to apologise for; it is the phenomenon the differential-algebra
literature calls a *ranking*. Wu's method is sensitive to the elimination order, and for a
differential problem the right order is the one that respects differentiation: `y < y' < y''
< …`. Supplying it removes the multiplier entirely. `wu_diff (order := 0)` also works here,
by not generating the fifth-order hypothesis that misleads the default ordering. -/

/-! #### Where prolongation becomes necessary

A solution of `E(L) = 0` satisfies every derivative of it — that is what closure of the
differential ideal under `D` means. The hypothesis is fourth order; the goals are fifth and
sixth, so now the hand proof has to manufacture the prolongations itself. -/

/-- **First prolongation — by hand.** One `congrArg`, one expansion, then the cofactor. -/
theorem prolonged_once_by_hand (y : R)
    (h : y′′′′ + y′′ + 2 * y ^ 3 = 0) :
    y′′′′′ + y′′′ + 6 * (y ^ 2 * y′) = 0 := by
  have h' : (y′′′′ + y′′ + 2 * y ^ 3)′ = (0 : R)′ := Wu.deriv_congr h
  simp only [map_add, map_zero, Derivation.leibniz, Derivation.leibniz_pow, smul_eq_mul,
    nsmul_eq_mul, Nat.cast_ofNat, Derivation.map_ofNat, mul_zero, add_zero,
    Nat.add_one_sub_one] at h'
  linear_combination h'

/-- **The same, by `wu_diff`**, which prolongs by default. -/
theorem prolonged_once_by_wu (y : R)
    (h : y′′′′ + y′′ + 2 * y ^ 3 = 0) :
    y′′′′′ + y′′′ + 6 * (y ^ 2 * y′) = 0 := by
  wu_diff

/-- **Second prolongation.** Two `congrArg`s, and a Leibniz expansion with a product rule
inside a product rule. `wu_diff (order := 2)` is the whole proof. -/
theorem prolonged_twice_by_wu (y : R)
    (h : y′′′′ + y′′ + 2 * y ^ 3 = 0) :
    y′′′′′′ + y′′′′ + 12 * (y * (y′) ^ 2) + 6 * (y ^ 2 * y′′) = 0 := by
  wu_diff (order := 2)

/-! #### The second-order case, for scale

The classical harmonic oscillator, which is the `L = (y')² − y²` member of the same story.
This is the goal that exposed the missing goal-expansion: before `Wu.expandGoal`, `wu_diff`
failed on it outright. -/

/-- Energy conservation for `y'' + y = 0`. -/
theorem oscillator_energy (y : R) (h : y′′ + y = 0) : ((y′) ^ 2 + y ^ 2)′ = 0 := by
  wu_diff

end WuDifferential.VariationalWu
